# Generated by Django 5.0.2 on 2024-07-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_acessorio_categoria_cor_marca"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marca",
            name="nacionalidade",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
